### ISSUE TITLE
Bug #3: Zoom In, Zoom out lost control

### ISSUE THREAD

**Issue by hoangtc125** [MasterPi-2124/OOP#3]
Hàm Zoom In, Zoom Out thực hiện thay đổi tọa độ các điểm trong đồ thị bằng cách tình tiến k lần (hệ số k = 1.2) so với điểm trung tâm của DisplayPane (tọa độ x = 650, y = 300)

Problem: 
+ Khi Zoom In, kích cỡ đồ thị to vượt quá màn hình thì sẽ không có chức năng dịch chuyển đồ thị thị hướng kéo chuột, xử lý bằng cách Zoom Out nhưng kích cỡ mới chưa kiểm soát được (có thể bé hơn hệ số k nhiều lần)

**Comment by masterpi007** [comment]
bạn sửa đc chưa, chuyển sang zoom in cái pane đc ko?
@hoangtc125

**Comment by masterpi007** [comment]
I think it was fixed, cause there isn't enough information.
