### ISSUE TITLE
Suggestion: Migrate to MVC

### ISSUE THREAD

**Issue by masterpi007** [MasterPi-2124/OOP#5]
Collaborating in big projects is never an easy thing, especially when there are a lot of people. Apply MVC to this project will help us collaborate seamlessly and never worry about code conflict.

@trandai1106 will take care of this son. Good luck!

**Comment by trandai1106** [comment]
The project has been restructured according to the MVC model. In addition to models, views, and controllers, I added a package called algorithms to contain classes that handle logic. 
Specifically, the GDF package includes sub packages and components:

1. GDF.models
+ Edge.java
+ Graph.java
+ Vertex.java

2. GDF.views
+ About.fxml
+ Main.fxml
+ Draw.fxml
+ design.css

3. GDF.controllers
+ DrawSceneController.java
+ InformationSceneController.java
+ MainSceneController.java

4. GDF.algorithms
+ AllPath.java
+ DFS_BFS.java

The main class MyMain.java is located in the package GDF.
